version: "3.9"

services:
  db:
    image: postgres:15
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    env_file: .env
    command: flask run --host=${FLASK_RUN_HOST} --port=${FLASK_RUN_PORT}
    volumes:
      - ./app:/app
    ports:
      - "${FLASK_RUN_PORT}:${FLASK_RUN_PORT}"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
